### PR TITLE
Fix timelapse chart throwing an error

### PR DESCRIPTION
**Pull request by StefanVanDyck**
When trying to play the timelapse chart in regions we were getting an error dialog box.
This was caused by the SOLR range query containing unencoded square brackets.
Simply making sure that part of the query is also encoded should fix things.

### CODE REVIEW

**Comment by StefanVanDyck** [comment]
I think with the last commit, I finally got most of the places that were missing urlencoding for the request parameters.

**Comment by adam-collins** [comment]
I failed to reproduce the url encode errors. More details to reproduce are required.

I did find various time control issues, see #107.

**Comment by StefanVanDyck** [comment]
Thanks for having a look @adam-collins .

[I _suspect_ the reason I was having issues is that I am using AWS ALB as reverse proxy.](https://stackoverflow.com/questions/51941139/aws-api-gateway-returns-400-error-when-square-bracket-is-in-path)
And that things like nginx and grails itself actually have no issue with square brackets in the URI.

According to the standard square brackets are not supported however and including this "fix" might help other people that encounter similar issues.

I'll make sure to merge the improvements you made on #107  into this branch.

Please tell me f you would like me to make any other changes or add some testing before accepting the PR.

**Review by adam-collins — APPROVED** [review]
No issues found. 

I failed to replicate the issue but additional encoding is always good.

**Pull request merged**
